### ISSUE TITLE
Return type for list vs typing.List

### ISSUE THREAD

**Issue by frecar** [ipeterov/strict_types#1]
Hi, if I create the following function:

```
from typing import List

@strict_types
def convert_to_list(name: str) -> List[str]:
    return [name]

print(convert_to_list("test"))
```

I get the following exception: 

```
TypeError: Type of result is <class 'list'> and not typing.List[str]
```

Which of course is (somehow) correct, but not desirable.

Is this something you are planning to support? :)

**Comment by ipeterov** [comment]
Yes, the current behavior seems wrong. I'll start working on it right now.

**Comment by frecar** [comment]
Cool :)

**Comment by ipeterov** [comment]
It should work properly now. BTW, thank you for pointing it out:)
